### ISSUE TITLE
Question on generating the ground truth  `w0` 

### ISSUE THREAD

**Issue by yanconglin** [zhou13/nerd#3]
HI, Yichao,

I am having some trouble understading this line:
https://github.com/zhou13/symmetrynet/blob/830bd9430c1750d31faffba60e18b075374c1b42/sym/datasets.py#L95

If I understand correctly, w0 is the the ground truth w. As you mentioned the shapenet objects are symmetrically aligned w.r.t Y-Z (x=0) plane, I suppose this line should be  `w0_ = LA.inv(RT).T @ np.array([1, 0, 0, 0])`.  Or am I completely wrong? 

BTW, many congrats on your promotion! Impressive work!
Looking forward to your reply.

Yancong

**Comment by zhou13** [comment]
Hi Yancong,

Thanks for asking. The problem here is that ShapeNet releases in the obj format and it seems that obj wavefront specification only says things about "forward direction" and "upward direction" rather than xyz axes. Therefore, different software has different mapping for xyz for obj files: See the difference between blender and meshlab:

![image](https://user-images.githubusercontent.com/576382/105769835-67d2cc80-5f2c-11eb-951f-692f74452389.png)

The implementation here uses the blender convention. We will update the paper accordingly to avoid confusion. Nice catch!

Best,
Yichao Zhou

**Comment by yanconglin** [comment]
Thanks very much for your answer! I will look into the details. Issue closed for now.

**Comment by njnj0314** [comment]
Hello, I recently read this paper, download the dataset encountered some problems, please ask you have this paper dataset?
